xmpp_accounts/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of django-xmpp-register (https://account.jabber.at/doc).
#
# django-xmpp-register is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# django-xmpp-register is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# django-xmpp-register.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import unicode_literals, absolute_import

from django.conf.urls import url

from . import views

app_name = 'xmpp_accounts'

urlpatterns = [
    url(r'^$', views.RegistrationView.as_view(), name='register'),
    url(r'^register/confirm/(?P<key>\w+)/$', views.RegistrationConfirmationView.as_view(),
        name='register_confirm'),
    url(r'^password/$', views.ResetPasswordView.as_view(), name='password'),
    url(r'^password/confirm/(?P<key>\w+)/$', views.ResetPasswordConfirmationView.as_view(),
        name='password_confirm'),
    url(r'^email/$', views.ResetEmailView.as_view(), name='email'),
    url(r'^email/confirm/(?P<key>\w+)/$', views.ResetEmailConfirmationView.as_view(),
        name='email_confirm'),
    url(r'^delete/$', views.DeleteView.as_view(), name='delete'),
    url(r'^delete/confirm/(?P<key>\w+)/$', views.DeleteConfirmationView.as_view(),
        name='delete_confirm'),
    url(r'^api/user-available/$', views.UserAvailableView.as_view(), name='api-user-available'),

]

xmppaccount/urls.py
# -*- coding: utf-8 -*-
# vim: expandtab:tabstop=4:hlsearch
#
# This file is part of django-xmpp-account (https://github.com/mathiasertl/django-xmpp-account/).
#
# django-xmpp-account is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# django-xmpp-account is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
# the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # for captchas:
    url(r'^captcha/', include('captcha.urls')),

    # admin interface
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('xmpp_accounts.urls')),
]

for path, include_args in settings.EXTRA_URL_INCLUDES.items():
    urlpatterns.append(url(path, include(*include_args)))

core/views.py
# -*- coding: utf-8 -*-
# vim: expandtab:tabstop=4:hlsearch
#
# This file is part of django-xmpp-account (https://github.com/mathiasertl/django-xmpp-account/).
#
# django-xmpp-account is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# django-xmpp-account is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
# the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with django-xmpp-account.
# If not, see <http://www.gnu.org/licenses/>.

from __future__ import unicode_literals

import logging

from django.conf import settings
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.six.moves.urllib.parse import urlsplit
from django.utils.translation import ugettext as _
from django.views.generic import FormView

from brake.decorators import ratelimit

from xmpp_backends.base import UserExists
from xmpp_backends.base import UserNotFound

from core.exceptions import GpgError
from core.exceptions import RateException
from core.exceptions import SpamException
from core.models import Address
from core.models import Confirmation
from core.models import UserAddresses
from core.tasks import send_email
from core.utils import confirm
from core.utils import get_client_ip

User = get_user_model()
log = logging.getLogger(__name__)


class AntiSpamFormView(FormView):
    action_url = None

    def dispatch(self, request, *args, **kwargs):
        remote_ip = get_client_ip(request)

        if settings.DEBUG is False and remote_ip not in settings.RATELIMIT_WHITELIST:
            # create a dummy function and dynamically set its name. This way,
            # the ratelimit decorator is specific to the method in each class.
            def func(request):
                pass
            func.__name__ = str('%s_dispatch' % self.__class__.__name__)
            func = ratelimit(method='POST', rate='15/m')(func)
            ratelimit(method='GET', rate='40/m')(func)(request)

            if getattr(request, 'limited', False):
                raise RateException()

        # We sometimes get requests *without* a user agent. We assume these are automated requests.
        if not request.META.get('HTTP_USER_AGENT'):
            raise SpamException("No user agent passed.")

        return super(AntiSpamFormView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AntiSpamFormView, self).get_context_data(**kwargs)
        context['menuitem'] = getattr(self, 'menuitem', None)

        # Social media
        action_url = self.action_url
        if action_url is not None:
            action_url = reverse(action_url)
        context['ACTION_URL'] = self.request.build_absolute_uri(action_url)
        context['REGISTER_URL'] = self.request.build_absolute_uri('/')

        if 'CANONICAL_HOST' in self.request.site:
            context['ACTION_URL'] = urlsplit(context['ACTION_URL'])._replace(
                netloc=self.request.site['CANONICAL_HOST']).geturl()
            context['REGISTER_URL'] = urlsplit(context['REGISTER_URL'])._replace(
                netloc=self.request.site['CANONICAL_HOST']).geturl()

        context['OPENGRAPH_TITLE'] = self.opengraph_title % self.request.site
        context['OPENGRAPH_DESCRIPTION'] = self.opengraph_description % self.request.site
        context['TWITTER_TEXT'] = getattr(self, 'twitter_text', context['OPENGRAPH_TITLE'])

        form = context['form']
        if settings.GPG and hasattr(form, 'cleaned_data') and 'gpg_key' in form.fields:
            if form['gpg_key'].errors or form['fingerprint'].errors or \
                    form.cleaned_data.get('fingerprint') or form.cleaned_data.get('gpg_key'):
                context['show_gpg'] = True
        return context

    def get_form_kwargs(self):
        kwargs = super(AntiSpamFormView, self).get_form_kwargs()

        if 'username' in self.form_class.declared_fields:
            kwargs['initial']['username'] = '@%s' % self.request.site['DOMAIN']
        return kwargs

    def form_valid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class ConfirmationView(AntiSpamFormView):
    user_not_found_error = _("User not found (or false password provided)!")

    def handle_valid(self, form, user):
        """By default, the users current fingerprint is the payload."""

        return {
            'gpg_fingerprint': user.gpg_fingerprint,
            'username': user.node,
            'domain': user.domain,
        }

    def handle_gpg(self, form, user):
        if not settings.GPG:
            return {}  # shortcut

        if form.cleaned_data.get('fingerprint'):
            fingerprint = form.cleaned_data['fingerprint']

            return {'gpg_fingerprint': fingerprint, }
        elif 'gpg_key' in self.request.FILES:
            path = self.request.FILES['gpg_key'].temporary_file_path()
            with open(path) as stream:
                data = stream.read()
            return {'gpg_key': data, }
        else:
            return {'gpg_fingerprint': None, }

    def form_valid(self, form):
        try:
            user = self.get_user(form.cleaned_data)
            payload = self.handle_valid(form, user)
        except GpgError as e:
            form.add_error(e.field, e.message)
            return self.form_invalid(form)
        except User.DoesNotExist:
            form.add_error(None, self.user_not_found_error)
            return self.form_invalid(form)
        except UserNotFound as e:
            if e.args and e.args[0]:
                form.add_error(None, e.args[0].encode('utf-8'))
            else:
                form.add_error(None, self.user_not_found_error)
            return self.form_invalid(form)

        # log user address:
        address = Address.objects.get_or_create(address=self.request.META['REMOTE_ADDR'])[0]
        UserAddresses.objects.create(address=address, user=user, purpose=self.purpose)

        # Send confirmation email to the user
        key, kwargs = confirm(self.request, user, purpose=self.purpose, payload=payload)
        if settings.BROKER_URL is None:
            key.send(**kwargs)
        else:
            send_email.delay(key_id=key.pk, **kwargs)

        return super(ConfirmationView, self).form_valid(form)


class ConfirmedView(AntiSpamFormView):
    user = None

    def dispatch(self, request, *args, **kwargs):
        if request.META.get('HTTP_USER_AGENT', '').startswith('Twitterbot'):
            return HttpResponseRedirect(reverse(self.action_url))
        return super(ConfirmedView, self).dispatch(request, *args, **kwargs)

    def after_delete(self, data):
        pass

    def get_context_data(self, **kwargs):
        context = super(ConfirmedView, self).get_context_data(**kwargs)
        if self.user is not None:
            context['username'] = self.user.node
            context['domain'] = self.user.domain
            context['jid'] = self.user.jid
        return context

    def form_valid(self, form):
        try:
            key = Confirmation.objects.valid().filter(
                purpose=self.purpose).get(key=self.kwargs['key'])
        except Confirmation.DoesNotExist:
            form.add_error(None, _("Confirmation key expired or not found."))
            return self.form_invalid(form)
        self.user = key.user

        try:
            self.handle_key(key, form)
            key.delete()
            self.after_delete(form.cleaned_data)
        except UserNotFound as e:
            if e.message:
                form.add_error(None, _("User not found: %s") % e.message)
            else:
                form.add_error(None, _("User not found!"))
            return self.form_invalid(form)
        except UserExists:
            form.add_error(None, _("User already exists!"))
            return self.form_invalid(form)

        return super(ConfirmedView, self).form_valid(form)

core/templates/base.html
{% load staticfiles i18n social%}<!DOCTYPE html>
<html><head>
    <title>{{ request.site.DOMAIN }} | {% block pagetitle %}{% endblock pagetitle %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
{% comment %}Dublin Core{% endcomment %}
    <meta name="DC.Title" content="{{ TWITTER_TEXT }}" >
    <meta name="DC.Subject" content="jabber, xmpp, Instant Messaging" >
{% comment %}Facebook Open Graph{% endcomment %}
    <meta property="og:type"   content="article" /> 
    <meta property="og:title" content="{{ OPENGRAPH_TITLE }}" />
    <meta property="og:url" content="{% if ACTION_URL %}{{ ACTION_URL }}{% else %}/{% endif %}" />
    {% if request.site.FACEBOOK_IMAGE %}<meta property="og:image" content="{{ request.site.FACEBOOK_IMAGE }}" />{% endif %}
    <meta property="og:description" content="{{ OPENGRAPH_DESCRIPTION }}" />
    {% if request.site.FACEBOOK %}
    <meta property="article:author" content="https://facebook.com/{{ request.site.FACEBOOK }}" />
    <meta property="article:publisher" content="https://facebook.com/{{ request.site.FACEBOOK }}" />
    {% endif %}
{% comment %}Twitter cards{% endcomment %}{% if request.site.TWITTER and request.site.TWITTER_IMAGE %}
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="{{ TWITTER_TEXT }}" />
    <meta name="twitter:site" content="@{{ request.site.TWITTER }}" />
    <meta name="twitter:image" content="{{ request.site.TWITTER_IMAGE }}" />
    <meta name="twitter:url" content="{{ ACTION_URL }}" />{% comment %}NOTE: Documented but unsed by twitter{% endcomment %}

    <meta name="xmpp-accounts:api-user-available" content="{% url "xmpp_accounts:api-user-available" %}" />
{% endif %}

    <style>
        @font-face {
            font-family: FontAwesome;
            src:url({% static "lib/font-awesome/fonts/fontawesome-webfont.eot" %});
            src:url({% static "lib/font-awesome/fonts/fontawesome-webfont.eot" %}#iefix&v=4.3.0)
                    format('embedded-opentype'),
                url({% static "lib/font-awesome/fonts/fontawesome-webfont.woff2" %})
                    format('woff2'),
                url({% static "lib/font-awesome/fonts/fontawesome-webfont.woff" %})
                    format('woff'),
                url({% static "lib/font-awesome/fonts/fontawesome-webfont.ttf" %})
                    format('truetype'),
                url({% static "lib/font-awesome/fonts/fontawesome-webfont.svg" %})
                    format('svg');
            font-weight: 400;
            font-style: normal;
        }
    </style>
{% if debug %}
    <script src="{% static "lib/jquery/jquery.js" %}"></script>
    <script src="{% static "lib/bootstrap/js/bootstrap.js" %}"></script>
    <script src="{% static "js/base.js" %}"></script>
    <link rel="stylesheet" href="{% static "lib/bootstrap/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "lib/font-awesome/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "lib/shariff/shariff.min.css" %}">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {{ form.media }}
{% else %}
    <script src="{% static MINIFIED_JS %}"></script>
    <link rel="stylesheet" href="{% static MINIFIED_CSS %}">
{% endif %}
    <script>
        var csrftoken = "{{ csrf_token }}";
        var captcha_refresh_url = "{% url 'captcha-refresh' %}";
        var MIN_USERNAME_LENGTH = {{ MIN_USERNAME_LENGTH }};
        var MAX_USERNAME_LENGTH = {{ MAX_USERNAME_LENGTH }};
        {% if SITE.FACEBOOK %}var FACEBOOK_PAGE = "{{ SITE.FACEBOOK }}";{% endif %}
        {% if SITE.TWITTER %}var TWITTER_PAGE = "{{ SITE.TWITTER }}";{% endif %}
        {% if SITE.GPLUS %}var GPLUS_PAGE = "{{ SITE.GPLUS }}";{% endif %}
    </script>
    <!-- custom code -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
</head><body class="{{ menuitem }}">
<div id="fb-root"></div>
<div class="container">
{% block container %}
{% include "core/includes/navbar.html" %}
<div class="page-header"><h1>{% block title %}{% endblock title %}</h1></div>
{% block social %}{% social %}{% endblock social %}

{% block body %}{% endblock body %}
<footer class="row"><div class="col-md-12">
    <p>{% trans "© 2013 - 2015, Mathias Ertl unless otherwise noted." %}
    <a href="http://flattr.com/thing/3969667/jabber-at-Jabber-for-everyone" target="_blank"><img id="flattr" src="{% static 'img/flattr-badge-large.png' %}" alt="Flattr this" title="Flattr this" /></a>
    </p>
    <p>{% blocktrans %}This project is powered by <a href="https://www.djangoproject.com">Django</a>.
    Source code and documentation is available <a href="https://github.com/mathiasertl/django-xmpp-account">on GitHub</a>.{% endblocktrans %}</p>
</div></footer>
{% endblock container %}
</div>
<script>{% comment %}fake shariff for noauto class to enable manual buttons{% endcomment %}
$('.shariff.noauto').each(function() {
    this.shariff = 'exists';
});
</script>
<script src="{% static "lib/shariff/shariff.min.js" %}"></script>
</body></html>